apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: swarms.k8-lab.info
spec:
  group: k8-lab.info
  scope: Namespaced
  names:
    plural: swarms
    singular: swarm
    kind: Swarm
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - replicas
              properties:
                replicas:
                  type: integer
                  minimum: 1
                size:
                  type: integer
                peers:
                  type: array
                  additionalProperties:
                    type: object
                    required:
                      - id
                      - address
                      - created_at
                    properties:
                      index:
                        type: integer
                      id:
                        type: string
                      address:
                        type: string
                      created_at:
                        type: integer
                      state:
                        type: object
                        properties:
                          phase:
                            type: string

      additionalPrinterColumns:
        - name: Replicas
          type: integer
          description: The number of desired peers in the raft swarm
          jsonPath: .spec.replicas
        - name: Size
          type: integer
          jsonPath: .spec.size
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp